### ISSUE TITLE
TM1py.Exceptions.Exceptions.TM1pyException: Text:  Status Code: 401 Reason: Unauthorized Headers

### ISSUE THREAD

**Issue by lieslberry** [MariusWirtz/tm1-optipyzer#3]
Hi

I am trying to test the TM1Optipyzer, but I am now getting this error. I am not sure how to troubleshoot this?

I am just using the UX_Samples to test.

Please help me.

**Comment by lieslberry** [comment]
Just to add. I tried the check.py and it worked.

**Comment by MariusWirtz** [comment]
Hi @lieslberry, 

you get the 401 Unauthorized response when you provide wrong credentials.
Please check the `config.ini` file if it has the same credentials, that you provided in the `check.py` script.

**Comment by lieslberry** [comment]
Hi Marius

Yes I have given the same credentials as the check.py one.
